#!/bin/bash
CLUSTERNAME=mycluster
CI_EMAIL=mmosesohn+ci@mirantis.com

GERRIT_SERVER=https://review.fuel-infra.org
GERRIT_SHORTNAME=fuel-gerrit
JENKINS_SERVER=http://jenkins-storage.ng.mirantis.net

#Required for generic gate
DNS_SERVERS=172.18.80.136

#Now CLUSTERNAME-cluster-key
#SSH_KEY_ID=e4fbb86b-0f5e-4670-a88f-c906a5e38014
